import type { SkillOptimizationBaseArmParams } from '@shared/types/data';

export const TOP_K_MULTIPLIER = 50;

export const BaseArmsParams: SkillOptimizationBaseArmParams[] = [
  {
    temperature_min: 0,
    temperature_max: 0.33,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 0.34,
    temperature_max: 0.66,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 0.67,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 0,
    temperature_max: 0.33,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.5,
    thinking_max: 0.5,
  },
  {
    temperature_min: 0.34,
    temperature_max: 0.66,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.5,
    thinking_max: 0.5,
  },
  {
    temperature_min: 0.67,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.5,
    thinking_max: 0.5,
  },
  {
    temperature_min: 0,
    temperature_max: 0.33,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 1,
    thinking_max: 1,
  },
  {
    temperature_min: 0.34,
    temperature_max: 0.66,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 1,
    thinking_max: 1,
  },
  {
    temperature_min: 0.67,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 1,
    thinking_max: 1,
  },
];
