import { z } from 'zod';

export const EmbeddingData = z.object({
  /**
   * The object type, which is always "embedding".
   */
  object: z.literal('embedding'),

  /**
   * The embedding vector, which is a list of floats. The length of vector depends on the model as listed in the embedding guide.
   */
  embedding: z.array(z.number()),

  /**
   * The index of the embedding in the list of embeddings.
   */
  index: z.number(),
});

export type EmbeddingData = z.infer<typeof EmbeddingData>;

export const EmbeddingsUsage = z.object({
  /**
   * The number of tokens used by the prompt.
   */
  prompt_tokens: z.number(),

  /**
   * The total number of tokens used by the request.
   */
  total_tokens: z.number(),
});

export type EmbeddingsUsage = z.infer<typeof EmbeddingsUsage>;

export const CreateEmbeddingsResponseBody = z.object({
  /**
   * The object type, which is always "list".
   */
  object: z.literal('list'),

  /**
   * The list of embeddings generated by the model.
   */
  data: z.array(EmbeddingData),

  /**
   * The name of the model used to generate the embedding.
   */
  model: z.string(),

  /**
   * The usage information for the request.
   */
  usage: EmbeddingsUsage,
});

export type CreateEmbeddingsResponseBody = z.infer<
  typeof CreateEmbeddingsResponseBody
>;

export const CreateEmbeddingsError = z.object({
  /**
   * The error message.
   */
  message: z.string(),

  /**
   * The error type.
   */
  type: z.string(),

  /**
   * The error parameter that caused the issue.
   */
  param: z.string().optional(),

  /**
   * The error code.
   */
  code: z.string().optional(),
});

export type CreateEmbeddingsError = z.infer<typeof CreateEmbeddingsError>;

export const CreateEmbeddingsErrorResponseBody = z.object({
  /**
   * The error object.
   */
  error: CreateEmbeddingsError,
});

export type CreateEmbeddingsErrorResponseBody = z.infer<
  typeof CreateEmbeddingsErrorResponseBody
>;
