import type { BaseArm } from '@shared/types/data';

export const BaseArms: BaseArm[] = [
  // Default for most models
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Default for most models with thinking
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 1,
    thinking_max: 1,
  },

  // Temperature variations (creativity control)
  {
    temperature_min: 0,
    temperature_max: 0.33,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 0.34,
    temperature_max: 0.66,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 0.67,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Top-p variations (diversity control)
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0,
    top_p_max: 0.33,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.34,
    top_p_max: 0.66,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.67,
    top_p_max: 1,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Top-k variations (diversity control)
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0.33,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0.34,
    top_k_max: 0.66,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0.67,
    top_k_max: 1,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Frequency Penalty variations
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0.33,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.34,
    frequency_penalty_max: 0.66,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.67,
    frequency_penalty_max: 1,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Presence Penalty variations
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0.33,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0.34,
    presence_penalty_max: 0.66,
    thinking_min: 0,
    thinking_max: 0,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0.67,
    presence_penalty_max: 1,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Thinking variations
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0.33,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.34,
    thinking_max: 0.66,
  },
  {
    temperature_min: 1,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.67,
    thinking_max: 1,
  },

  // Mixed variations
  // Lower temperature, light thinking
  {
    temperature_min: 0.5,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.0,
    thinking_max: 0.33,
  },

  // Lower temperature, medium thinking
  {
    temperature_min: 0.5,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.34,
    thinking_max: 0.66,
  },

  // Lower temperature, high thinking
  {
    temperature_min: 0.5,
    temperature_max: 1,
    top_p_min: 0.5,
    top_p_max: 0.5,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0.34,
    presence_penalty_max: 0.66,
    thinking_min: 0.67,
    thinking_max: 1,
  },

  // Real-world configurations commonly used in production

  // Code generation (balanced creativity, minimal repetition)
  {
    temperature_min: 0.2,
    temperature_max: 0.2,
    top_p_min: 0.95,
    top_p_max: 0.95,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.1,
    frequency_penalty_max: 0.1,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Creative writing (high creativity, some repetition control)
  {
    temperature_min: 0.8,
    temperature_max: 0.8,
    top_p_min: 0.9,
    top_p_max: 0.9,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.2,
    frequency_penalty_max: 0.2,
    presence_penalty_min: 0.1,
    presence_penalty_max: 0.1,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Analytical/reasoning tasks (low temperature, nucleus sampling)
  {
    temperature_min: 0.1,
    temperature_max: 0.1,
    top_p_min: 0.9,
    top_p_max: 0.9,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 1,
    thinking_max: 1,
  },

  // Conversational assistant (balanced, natural responses)
  {
    temperature_min: 0.7,
    temperature_max: 0.7,
    top_p_min: 1,
    top_p_max: 1,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Question answering (deterministic, focused)
  {
    temperature_min: 0,
    temperature_max: 0,
    top_p_min: 1,
    top_p_max: 1,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.5,
    thinking_max: 0.5,
  },

  // Brainstorming (high creativity, diverse ideas)
  {
    temperature_min: 0.9,
    temperature_max: 0.9,
    top_p_min: 0.8,
    top_p_max: 0.8,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.3,
    frequency_penalty_max: 0.3,
    presence_penalty_min: 0.3,
    presence_penalty_max: 0.3,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Technical documentation (consistent, clear)
  {
    temperature_min: 0.3,
    temperature_max: 0.3,
    top_p_min: 0.95,
    top_p_max: 0.95,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.05,
    frequency_penalty_max: 0.05,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Data analysis/summarization (balanced, thorough)
  {
    temperature_min: 0.4,
    temperature_max: 0.4,
    top_p_min: 0.9,
    top_p_max: 0.9,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.8,
    thinking_max: 0.8,
  },

  // Math/logic problems (deterministic with thinking)
  {
    temperature_min: 0,
    temperature_max: 0,
    top_p_min: 1,
    top_p_max: 1,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 1,
    thinking_max: 1,
  },

  // Content moderation (conservative, consistent)
  {
    temperature_min: 0.1,
    temperature_max: 0.1,
    top_p_min: 0.95,
    top_p_max: 0.95,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0.3,
    thinking_max: 0.3,
  },

  // Translation (balanced accuracy and fluency)
  {
    temperature_min: 0.3,
    temperature_max: 0.3,
    top_p_min: 1,
    top_p_max: 1,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0,
    frequency_penalty_max: 0,
    presence_penalty_min: 0,
    presence_penalty_max: 0,
    thinking_min: 0,
    thinking_max: 0,
  },

  // Role-play/character generation (creative with some consistency)
  {
    temperature_min: 0.85,
    temperature_max: 0.85,
    top_p_min: 0.95,
    top_p_max: 0.95,
    top_k_min: 0,
    top_k_max: 0,
    frequency_penalty_min: 0.15,
    frequency_penalty_max: 0.15,
    presence_penalty_min: 0.2,
    presence_penalty_max: 0.2,
    thinking_min: 0,
    thinking_max: 0,
  },
];
